# Generated by Django 5.1.5 on 2025-02-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MySession',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='mysession_id',
            new_name='session_id',
        ),
    ]
