# Generated by Django 5.1.5 on 2025-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_mysession_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebatch',
            name='term',
            field=models.CharField(help_text='Eg: 22 - Term -1', max_length=11, verbose_name='Batch and Term'),
        ),
    ]
