# Generated by Django 5.1.5 on 2025-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_coursebatch_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebatch',
            name='term',
            field=models.CharField(help_text='Eg: 22 - Term -1', max_length=12, verbose_name='Batch and Term'),
        ),
    ]
