# Generated by Django 5.1.5 on 2025-02-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_coursebatch_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Fav_Subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
    ]
