# Generated by Django 5.1.5 on 2025-02-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_favsub_alter_attendance_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavSub',
        ),
    ]
