# Generated by Django 5.1.5 on 2025-02-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_delete_favsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('FavSub', models.CharField(max_length=15)),
            ],
        ),
    ]
