# Generated by Django 5.1.5 on 2025-02-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_favsub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavSub',
        ),
    ]
